version: "3"
services:
  authentication_server:
    container_name: authentication-api
    image: authentication_server
    restart: always
    build: .
    networks:
      backend: {}
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      backend: {}
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/db:/data/db
networks:
  backend:
    external: false
    name: backend