version: "3"
services:
  authentication_api:
    container_name: authentication-api
    restart: always
    build: .
    environment: :
      - MONGO_PORT = "${MONGO_PORT}"
      - MONGO_IP = "${MONGO_IP}"
      - HTTP_PORT = "${HTTP_PORT}"
      - HTTPS_PORT = "${HTTPS_PORT}"
      - MONGO_COLLECTION = "${MONGO_COLLECTION}"
      - ACCESS_TOKEN_SECRET = "${ACCESS_TOKEN_SECRET}"
      - ACCESS_TOKEN_EXPIRY = "${ACCESS_TOKEN_EXPIRY}"
    networks:
      backend: {}
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      backend: {}
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb/db:/data/db
networks:
  backend:
    external: false
    name: backend