version: "3"
services:
  authentication_server:
    container_name: authentication-api
    image: authentication_server
    restart: always
    build: .
    ports:
      - "4000:4000"
    external_links:
      - mongo
