
### Get users
GET http://localhost:4000/users
Content-Type: application/json

### Correct register
POST http://localhost:4000/register
Content-Type: application/json

{ 
    "username": "georgesquair@gmail.com",
    "password": "password"
}

### Correct login
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "georgesquair@gmail.com",
    "password": "password"
}

### Incorrect login
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "georgesquair@gmail.com",
    "password": "passwod"
}

### Delete user
POST http://localhost:4000/delete
Content-Type: application/json

{
    "username": "georgesquair@gmail.com"
}